//Ghadi Hassan Babour 19911463

/*my project is about a reservation system for a resturant called "LEMAREMA",
at first the home page will appear where the user can choose the background 
color and make a new reservation, the resturant accepts reservations for dinner
only(117 SR per person),to make a reservation the user must enter his name,
phone number,email,day,people number,and choose seat area(also ,can enter a 
discount code if he have).the total price will appear and the user can confirm 
his reservation ,the reservation will be completed and all his reservaton 
information will be written in a file.then all his reservations information will
be read from the file and displayed in text area.finally, the user can choose to
make a new reservation or to exit from the system*/

package a_1911463;

import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;

public class Frame1 extends javax.swing.JFrame {
    
    /*static background color so,all other frames can use this color to set
    their background*/
    public static Color bgColor = new Color(217,156,167);
    
    //constructor
    public Frame1() {
        initComponents();
        
        //add picture to label
        Icon pic = new ImageIcon(getClass().getResource("picture2.jpg"));
        picLabel.setIcon(pic);
        
        //set frame title
        setTitle("Frame1");
        
        //set background color
        bgPanel.setBackground(bgColor);
        
        //show frame1
        this.setVisible(true); 
    }
    
    //Main methode
    public static void main(String[] args) {
        //open frame1
        new Frame1();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        newResButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bgColorButton = new javax.swing.JButton();
        picLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(230, 177, 224));

        bgPanel.setBackground(new java.awt.Color(217, 156, 167));

        newResButton.setBackground(new java.awt.Color(77, 115, 104));
        newResButton.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        newResButton.setText("New Reservation");
        newResButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newResButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 48)); // NOI18N
        jLabel2.setText("Welcome To ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(77, 115, 104));
        jLabel3.setText("===================================");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(77, 115, 104));
        jLabel5.setText("===================================");

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 48)); // NOI18N
        jLabel4.setText("reservation System");

        bgColorButton.setBackground(new java.awt.Color(77, 115, 104));
        bgColorButton.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        bgColorButton.setText("Background Color");
        bgColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgColorButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 48)); // NOI18N
        jLabel6.setText(" LEMAREMA Resturant");

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(278, 278, 278))
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(newResButton)
                        .addGap(128, 128, 128)
                        .addComponent(bgColorButton))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel4))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addComponent(jLabel2))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(521, 521, 521)
                        .addComponent(picLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(47, 47, 47)
                .addComponent(picLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bgColorButton)
                    .addComponent(newResButton))
                .addGap(16, 16, 16)
                .addComponent(jLabel3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //action listener for "New Reservation" button
    private void newResButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newResButtonActionPerformed
        //close this frame and open frame2
        this.dispose();
        new Frame2();
    }//GEN-LAST:event_newResButtonActionPerformed

    //action listener for "Background Color" button
    private void bgColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgColorButtonActionPerformed
        //show the JColorChooser and let the user choose the color
        bgColor = JColorChooser.showDialog(null,"choose background color",bgColor);
        
        //set the background color
        bgPanel.setBackground(bgColor);
    }//GEN-LAST:event_bgColorButtonActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bgColorButton;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton newResButton;
    private javax.swing.JLabel picLabel;
    // End of variables declaration//GEN-END:variables
}
