package a_1911463;

import javax.swing.Icon;
import javax.swing.ImageIcon;

public class Frame4 extends javax.swing.JFrame {

    //constructor
    public Frame4() {
        initComponents();
        
        //add picture to label
        Icon pic = new ImageIcon(getClass().getResource("picture1.png"));
        picLabel.setIcon(pic);
        
        //set frame title
        setTitle("Frame4");
        
        //set background color
        bgPanel.setBackground(Frame1.bgColor);
        
        //show frame4
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bgPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        newResButton = new javax.swing.JButton();
        disResButton = new javax.swing.JButton();
        picLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        bgPanel.setBackground(new java.awt.Color(217, 156, 167));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 48)); // NOI18N
        jLabel1.setText("Your reservation has been completed");

        newResButton.setBackground(new java.awt.Color(77, 115, 104));
        newResButton.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        newResButton.setText("New Reservation");
        newResButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newResButtonActionPerformed(evt);
            }
        });

        disResButton.setBackground(new java.awt.Color(77, 115, 104));
        disResButton.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        disResButton.setText("Display my Reservations");
        disResButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disResButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(77, 115, 104));
        jLabel2.setText("==================================");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(77, 115, 104));
        jLabel3.setText("==================================");

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 36)); // NOI18N
        jLabel4.setText("Waiting for you.....");

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(newResButton)
                        .addGap(49, 49, 49)
                        .addComponent(disResButton))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(417, 417, 417)
                        .addComponent(picLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(221, 221, 221))
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(picLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disResButton)
                    .addComponent(newResButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //action listener for "New Reservation" Button
    private void newResButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newResButtonActionPerformed
        //close this frame and open frame3
        this.dispose();
        new Frame3();
    }//GEN-LAST:event_newResButtonActionPerformed

    //action listener for "Display my Reservations" Button
    private void disResButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disResButtonActionPerformed
        //close this frame and open frame5
        this.dispose();
        new Frame5();
    }//GEN-LAST:event_disResButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JButton disResButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newResButton;
    private javax.swing.JLabel picLabel;
    // End of variables declaration//GEN-END:variables
}
